# Generated by Django 3.2.7 on 2021-09-24 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="añadido"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="actualizado",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="descripción"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BooksGenres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="añadido"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="actualizado",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="nombre"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BooksInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="añadido"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="actualizado",
                    ),
                ),
                (
                    "editorial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="editorial",
                    ),
                ),
                (
                    "publication_date",
                    models.IntegerField(
                        null=True, verbose_name="fecha de publicación"
                    ),
                ),
                (
                    "is_retired",
                    models.BooleanField(
                        default=False, verbose_name="¿Ésta retirado?"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="isbn"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("phy", "físico"), ("dig", "digital")],
                        max_length=3,
                        verbose_name="formato",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="books.books",
                        verbose_name="libro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books_add",
                        to="users.user",
                        verbose_name="añadido por",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="books",
            name="genre",
            field=models.ManyToManyField(
                related_name="genres",
                to="books.BooksGenres",
                verbose_name="género",
            ),
        ),
        migrations.AddIndex(
            model_name="booksinfo",
            index=models.Index(
                fields=["isbn", "editorial", "publication_date"],
                name="books_books_isbn_ee80f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="books",
            index=models.Index(
                fields=["name"], name="books_books_name_bb734e_idx"
            ),
        ),
    ]
